SELECT * FROM vehicle.product;


insert into vehicle.product values('0', 'DSI Tyers', 'DSI Resilient tyres have highest durability. In addition the steel rings of the base section ensure the perfect grip of the tyres and prevent skidding under extreme side loads.', 'https://www.laugfsindustrialtyres.com/images/optima.png', '10000');
insert into vehicle.product values('0', 'Engine Oil', 'Buy car engine oil from Castrol, Mobil and Petronas, with 5w30 oil and 10w40 oil in stock. Use our oil finder tool to find out which engine oil your car ', 'https://chevron.lk/wp-content/uploads/2013/06/4L-Hav-AP-ECO5-0W20-1.jpg', '1000');
insert into vehicle.product values('0', 'BLACKFIRE Foam Booster 16 oz', 'BLACKFIRE Foam Booster is a uniquely specialized formula that, when added to any car wash soap will instantly transform it into a foaming car wash!', 'https://sep.yimg.com/ay/autogeek/blackfire-foam-booster-16-oz-6.gif', '1500');
insert into vehicle.product values('0', 'Litro Gas', 'Litro Gas Lanka believes in a seamless engagement with customers. Our easy-to-remember four digits 1311 helpline gives customers the opportunity to instantly connect with us. ', 'https://www.litrogas.com/wp-content/uploads/2021/06/Home_Del_Logo-06__1_-removebg-preview.png', '2500');
insert into vehicle.product values('0', '3D Super Pre-Soak', '3D Super Pre-Soak will allow you to achieve a much higher level of clean with your weekly maintenance wash. The high pH formula of 3D Super rest on your paint faster than your standard car shampoo.', 'https://s.yimg.com/aah/autogeek/3d-super-pre-soak-6.gif', '1800');
insert into vehicle.product values('0', 'CARPRO Wash Box', ' The CARPRO Box Wash is ideal starter kit for anyone who’s ready to give their car a proper wash. The CARPRO Wash Box comes with Reset Intensive Car Shampoo, Elixir High Gloss Quick Detailer.', 'https://s.yimg.com/aah/autogeek/carpro-wash-box-37.gif', '2500');
insert into vehicle.product values('0', 'BLACKFIRE Car Wash', 'BLACKFIRE Car Wash cleans your vehicle and renews the shine every time you wash your car. BLACKFIRE tri-polymers replenish and reinforce existing paint protection.', 'https://sep.yimg.com/ay/autogeek/blackfire-wet-diamond-conditioning-shampoo-22.gif', '1200');
insert into vehicle.product values('0', 'DP Coating Maintenance Kit', 'This kit comes with the DP Coating Maintenance Wash that allows you wash your car in between detailing applications, that not only cleans you car but also boots existing coatings.', 'https://s.yimg.com/aah/autogeek/dp-coating-maintenance-kit-8.gif', '1700');
insert into vehicle.product values('0', 'DP Ceramic wash', 'DP Ceramic Wash is the wash you are looking for if you want a highly hydrophobic maintenance wash. After removing contaminants, DP Ceramic Wash provides a boost to your ceramic coating each time it is used.', 'https://s.yimg.com/aah/autogeek/dp-ceramic-wash-28.gif', '800');
insert into vehicle.product values('0', 'DP Ultimate Wash-N-Max', 'DP Ultimate Wash-N-Wax is the time saver you’ve been looking for. Washing your car is a time-consuming job all on its own, especially if you have a large car and waxing is a whole other beast. ', 'https://s.yimg.com/aah/autogeek/dp-wash-n-wax-8.gif', '1400');

